# DAV 5400 Module 3 Assignment

In [2]:
# Importing numpy package 
import numpy as np

#### Q1. Write a Python/NumPy code block that finds the distinct array items that exist in either array a or array b but which do not appear within both arrays:

####  Logic to find distinct items in two numpy arrays which not appear in both arrays. ?

- In order to find unique elements in both arrays we will use set operations. 

- Firstly we will find the union of both arrays (which will contain the unique values in both the arrays)      

-  Secondly we find the intersection of both arrays (which contains the elements which are present in both the arrays)

- Lastly we perform set difference for both of these arrays (which will contain the unique elements in both arrays but not common to them)

In [104]:
a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])

c=np.setdiff1d(np.union1d(a,b),np.intersect1d(a,b))

print(c)

[ 1  3  5  6  7  8  9 10]


#### Q2. Create the following 4x5 array using knowledge you have of Python’s / NumPy’s sequencing functionality so that you do not need to explicitly key in every integer value

####  Logic

- Firstly we use the numpy "arange" function to find the elements from "1" to "20" ("21" is not included )       

- Secondly we use the numpy "reshape" function to create a 2D array of 4 rows and 5 columns . We also specify the order to arrange the elements . 'F' order here stands for Fortan Order . This parameter is used to specify the order in which the elements should be arranged in the new reshaped array.


In [105]:
array = np.arange(1,21).reshape(4,5,order = 'F')
print(array)

[[ 1  5  9 13 17]
 [ 2  6 10 14 18]
 [ 3  7 11 15 19]
 [ 4  8 12 16 20]]


#### Q3. Write a Python/Numpy code block that adds to array a any items that are present in array b but not already present within array a.


####  Logic

- Firstly we use numpy "setdiff1d" to find the elements wthat are present in b but not in a.    

- Secondly we use the numpy "append" function which appends value to the end of the array. Note: Append does not occur in place , a new array is allocated and filled .So we need to assign the new value to our new array


In [106]:
a = np.array([12, 5, 7, 15, 3, 1, 8])
b = np.array([14, 6, 3, 11, 19, 12, 5, 3, 4])

a= np.append(a,np.setdiff1d(b,a))
print(a)

[12  5  7 15  3  1  8  4  6 11 14 19]


#### Q4.  The process of transforming a multidimensional array into a unidimensional array is referred to as “flattening”. Transform the 4x5 array shown above in Problem 2 into a unidimensional array such that the sequence of values contained within the array is as follows: 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20

####  Logic

- We use the numpy "flatten" function to collapse the array into 1 dimension

- Also pass the parameter 'F' to flatten in column major order . Note : We also want to append the original array with the new flattened array , so we are assigning it . 


In [107]:
array = array.flatten('F')
print(array)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


#### Q4. For this problem you will load a small data set to your online GitHub repository and then read it into a NumPy 2D array. You will then use the content that NumPy array to answer a series of analytical questions. 
1) Load the provided M3_Data.csv file to your online DAV 5400 Github Repository.
2) Then, from within your M3 Assignment Jupyter Notebook, read the data set from your Github repository and load it into a Pandas dataframe using the code snippet provided below.

In [3]:
import pandas
# suppress scientific notation
np.set_printoptions(suppress = True)
# read the data file from GitHub and convert to a NumPy ndarray object
# be sure to replace the ‘link_to_raw_copy of data file in your Github Repository’ placeholder shown below
# with a link to the “raw” version of the file you pushed to your online GitHub repository
nyc_water = pandas.read_csv('https://raw.githubusercontent.com/anagh3395/DAV5400/main/Module3/M3_Data.csv').to_numpy()
# verify you have an ndarray object
type(nyc_water)
nyc_water

array([[   1979. , 7102100. ,    1512. ,     213. ],
       [   1980. , 7071639. ,    1506. ,     213. ],
       [   1981. , 7089241. ,    1309. ,     185. ],
       [   1982. , 7109105. ,    1382. ,     194. ],
       [   1983. , 7181224. ,    1424. ,     198. ],
       [   1984. , 7234514. ,    1465. ,     203. ],
       [   1985. , 7274054. ,    1326. ,     182. ],
       [   1986. , 7319246. ,    1351. ,     185. ],
       [   1987. , 7342476. ,    1447. ,     197. ],
       [   1988. , 7353719. ,    1484. ,     202. ],
       [   1989. , 7344175. ,    1402. ,     191. ],
       [   1990. , 7335650. ,    1424. ,     194. ],
       [   1991. , 7374501. ,    1469. ,     199. ],
       [   1992. , 7428944. ,    1369. ,     184. ],
       [   1993. , 7506166. ,    1368.5,     182. ],
       [   1994. , 7570458. ,    1357.7,     179. ],
       [   1995. , 7633040. ,    1325.7,     174. ],
       [   1996. , 7697812. ,    1297.9,     169. ],
       [   1997. , 7773443. ,    1205.5,     1

#### Q4 a) Which year had the maximum per capita daily water consumption?

####  Logic 

- Firstly we use the numpy "max" function to calculate max value from the 3rd column (take all rows and 3rd column with slicing)

- Secondly we use numpy "where" function to check when the value in the 3rd column   

- Thirdly we run a for loop through the indexes and print the year for the corresponding max value

- Note: We could have used numpy argmax() function but it will return only the index of the first occurence. So it wont work perfectly for duplicate values

In [109]:
max_capita = np.max(nyc_water[:,3])
max_value_index = np.where(nyc_water[:,3] == max_capita )

#Note: We run the loop through max_value_index[0] because max_value_index is array of tuples
for index in max_value_index[0]:
    print("Year - ", nyc_water[index][0] , "\nMax per capita daily - " , max_capita, "Gallons per person per day\n")


Year -  1979.0 
Max per capita daily -  213.0 Gallons per person per day

Year -  1980.0 
Max per capita daily -  213.0 Gallons per person per day



#### Q4 b) Add a new column to the Numpy array containing the annual change in the population of the city from year to year.

####  Logic 

- Firstly we use the numpy "diff" function on the first column (population) which calculates differences for the adjacent values in the array . We also add "prepend" NAN for the first row.

- Secondly we append this column in the original numpy array .

- The second argument is the change column (we also reshape it to convert it into a column)

- The third argument is "axis" and we assign it to 1 that means we wanna append column wise.

In [110]:
annual_change = np.diff(nyc_water[:,1],prepend = np.NaN)
nyc_water = np.append(nyc_water, annual_change.reshape(-1,1),axis=1)
print(nyc_water)

[[   1979.  7102100.     1512.      213.        nan]
 [   1980.  7071639.     1506.      213.   -30461. ]
 [   1981.  7089241.     1309.      185.    17602. ]
 [   1982.  7109105.     1382.      194.    19864. ]
 [   1983.  7181224.     1424.      198.    72119. ]
 [   1984.  7234514.     1465.      203.    53290. ]
 [   1985.  7274054.     1326.      182.    39540. ]
 [   1986.  7319246.     1351.      185.    45192. ]
 [   1987.  7342476.     1447.      197.    23230. ]
 [   1988.  7353719.     1484.      202.    11243. ]
 [   1989.  7344175.     1402.      191.    -9544. ]
 [   1990.  7335650.     1424.      194.    -8525. ]
 [   1991.  7374501.     1469.      199.    38851. ]
 [   1992.  7428944.     1369.      184.    54443. ]
 [   1993.  7506166.     1368.5     182.    77222. ]
 [   1994.  7570458.     1357.7     179.    64292. ]
 [   1995.  7633040.     1325.7     174.    62582. ]
 [   1996.  7697812.     1297.9     169.    64772. ]
 [   1997.  7773443.     1205.5     155.    75

#### Q4 c) What is the median and variance of the population of the city during the time period represented within the data set?

In [115]:
# Using numpy "median" function to calculate median along the columns
median_array = np.median(nyc_water, axis = 0)
# Using numpy "var" function to calculate variance along the columns
variance_array = np.var(nyc_water,axis=0)

#Print the median and variance by accessing the index 1 from the respective arrays
print("Median of population\n",median_array[1])
print("\nVariance of population\n",variance_array[1])

Median of population
 7947660.0

Variance of population
 214014109798.73172


#### Q5 d) What was the average annual change in the population of the city? 

In [123]:
# Using numpy "mean" function to calculate average annual change in the population
# We use slicing , We select 5th column and select from 2nd row (because 1st row has "NAN")
mean_array = np.mean(nyc_water[1:,4])

#Print the average
print("Average Annual change in the population\n",mean_array)

Average Annual change in the population
 30867.925
